# Credentials Config Service — configuración de credenciales aceptadas
database:
  persistence: false

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ccs.lab-jdmonsalvel.com
      paths:
        - /
  tls:
    - secretName: ccs-tls
      hosts:
        - ccs.lab-jdmonsalvel.com

deployment:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m
