---
# Keyrock admin password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keyrock-admin-secret
  namespace: trust-anchor
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keyrock-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: /fiware/keyrock/admin-password
        property: password
---
# Keyrock DB password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keyrock-db-secret
  namespace: trust-anchor
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keyrock-db-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-password
      remoteRef:
        key: /fiware/keyrock/db-password
        property: password
---
# MySQL root password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-root-secret
  namespace: trust-anchor
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-root-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: /fiware/mysql/root-password
        property: password
---
# MongoDB root password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-root-secret
  namespace: provider
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mongodb-root-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: /fiware/mongodb/root-password
        property: password
