# keyrock-credentials: adminPassword + dbPassword (fiware/keyrock chart)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keyrock-credentials-es
  namespace: trust-anchor
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keyrock-credentials
    creationPolicy: Owner
  data:
    - secretKey: adminPassword
      remoteRef:
        key: /fiware/keyrock/admin-password
        property: password
    - secretKey: dbPassword
      remoteRef:
        key: /fiware/keyrock/db-password
        property: password
---
# mysql-credentials: mysql-root-password + mysql-password (bitnami/mysql chart)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials-es
  namespace: trust-anchor
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-credentials
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: /fiware/mysql/root-password
        property: password
    - secretKey: mysql-password
      remoteRef:
        key: /fiware/keyrock/db-password
        property: password
---
# mongodb-root-secret (bitnami/mongodb chart)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-root-secret-es
  namespace: provider
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mongodb-root-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: /fiware/mongodb/root-password
        property: password
