apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orion-ld.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orion-ld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orion-ld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orion-ld.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "false"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: orion-ld
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1026
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: ORIONLD_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingMongoSecret }}
                  key: mongo-uri
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
