apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-orion
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://fiware.github.io/helm-charts
      chart: orion
      targetRevision: "1.6.*"
      helm:
        valueFiles:
          - $values/gitops/values/provider/orion.yaml
    - repoURL: https://github.com/jdmonsalvel/tfm-fiware-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: provider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
