apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: kong
    targetRevision: "15.4.22"
    helm:
      values: |
        database: "off"
        replicaCount: 1
        ingressController:
          enabled: false
        kong:
          declarativeConfig: |
            _format_version: "3.0"
            _transform: true
            services:
              - name: orion-ld-service
                url: http://fiware-orion.provider.svc.cluster.local:1026
                connect_timeout: 10000
                read_timeout: 60000
                write_timeout: 60000
                routes:
                  - name: ngsi-ld-api
                    paths:
                      - /ngsi-ld
                      - /version
                    strip_path: false
                    preserve_host: true
            consumers:
              - username: fiware-dataspace-provider
                jwt_secrets:
                  - algorithm: HS256
                    key: fiware-dataspace-provider-app
                    secret: demo-jwt-secret-tfm-2026
            plugins:
              - name: jwt
                service: orion-ld-service
                config:
                  key_claim_name: iss
                  claims_to_verify:
                    - exp
              - name: cors
                service: orion-ld-service
                config:
                  origins:
                    - "*"
                  methods:
                    - GET
                    - POST
                    - PATCH
                    - DELETE
                    - OPTIONS
                  headers:
                    - Accept
                    - Authorization
                    - Content-Type
                    - Link
                    - NGSILD-Tenant
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hostname: orion.lab-jdmonsalvel.com
          path: /
          pathType: Prefix
          tls: true
          selfSigned: false
          existingTlsSecret: kong-orion-tls
        service:
          type: ClusterIP
          ports:
            proxyHttp: 8000
            proxyHttps: 8443
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        postgresql:
          enabled: false
        waitForDatabase: false
  destination:
    server: https://kubernetes.default.svc
    namespace: provider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
