apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: "3.2.0"
    helm:
      values: |
        image:
          repository: kong
          tag: "3.9"

        env:
          database: "off"
          nginx_worker_processes: "1"

        dblessConfig:
          config: |
            _format_version: "3.0"
            _transform: true
            services:
              - name: orion-ld-service
                url: http://fiware-orion.provider.svc.cluster.local:1026
                connect_timeout: 10000
                read_timeout: 60000
                write_timeout: 60000
                routes:
                  - name: ngsi-ld-api
                    paths:
                      - /ngsi-ld
                      - /version
                    strip_path: false
                    preserve_host: true
            consumers:
              - username: fiware-dataspace-provider
                jwt_secrets:
                  - algorithm: HS256
                    key: fiware-dataspace-provider-app
                    secret: demo-jwt-secret-tfm-2026
            plugins:
              - name: jwt
                service: orion-ld-service
                config:
                  key_claim_name: iss
                  claims_to_verify:
                    - exp

        ingressController:
          enabled: false

        proxy:
          enabled: true
          type: ClusterIP
          ingress:
            enabled: false
            ingressClassName: nginx
            hostname: orion.lab-jdmonsalvel.com
            path: /
            pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            tls: orion-tls

        admin:
          enabled: false

        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: provider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
