apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: kong
      targetRevision: "15.4.22"
      helm:
        valueFiles:
          - $values/gitops/values/provider/kong.yaml
    - repoURL: https://github.com/jdmonsalvel/tfm-fiware-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: provider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
