apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: "14.12.0"
    helm:
      values: |
        fullnameOverride: mongodb
        image:
          registry: docker.io
          repository: mongo
          tag: "7.0"
          pullPolicy: IfNotPresent
        auth:
          enabled: false
        persistence:
          enabled: false
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: provider
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
