apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mysql
      targetRevision: "14.*"
      helm:
        valueFiles:
          - $values/gitops/values/trust-anchor/mysql.yaml
    - repoURL: https://github.com/jdmonsalvel/tfm-fiware-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: trust-anchor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
