apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: "9.23.0"
    helm:
      values: |
        fullnameOverride: mysql
        image:
          tag: "8.0.39-debian-12-r0"
        auth:
          existingSecret: mysql-credentials
          database: idm
          username: keyrock
        primary:
          persistence:
            enabled: false
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: trust-anchor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
